<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Concerned about live' => '关注直播',
    'Action' => '操作',
    'Amount of the transaction' => '交易金额',
    'Answered the question' => '回答问题',
    'Ask questions' => '提问',
    'Credit Manage' => '积分管理',
    'His' => '他',
    'My' => '我',
    'Source Subject' => '来源',
    'Transaction Hour' => '交易时间',
    'Your current credits are:' => '您当前的积分数为：',
    'answer is adopted' => '答案被采纳',
    'records' => '条记录',
    '{who} Credit' => '{who}的积分',
];
